#Criação do serviço web e imagem do docker 

services:
  web:
    build: ./app
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=postgresql://admin:nuvem123@db:5432/projeto_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=nuvem123
      - POSTGRES_DB=projeto_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql